### ISSUE TITLE
GPU 1개일 경우 세팅

### ISSUE THREAD

**Issue by ur-luella** [sooftware/KoSpeech#27]
안녕하세요!
보내주신 가중치를 가지고 evaluation을 진행하던 중에
아래와 같은 에러가 발생하였습니다.

구글링을 해봤을 때 코드는 gpu의 갯수가 기본으로 2개 이상 세팅되어 있는데
제가 돌려본 colab은 gpu를 1개만 제공하고 있어서 index가 나갔다는 내용을 찾았는데
코드를 어떻게 수정해야할까요?ㅠ

감사합니다!

```{python}
[2020-06-23 06:30:41,321 utils.py:21 - info()] --mode: eval
[2020-06-23 06:30:41,321 utils.py:21 - info()] --sample_rate: 16000
[2020-06-23 06:30:41,321 utils.py:21 - info()] --window_size: 20
[2020-06-23 06:30:41,321 utils.py:21 - info()] --stride: 10
[2020-06-23 06:30:41,321 utils.py:21 - info()] --n_mels: 80
[2020-06-23 06:30:41,321 utils.py:21 - info()] --normalize: True
[2020-06-23 06:30:41,321 utils.py:21 - info()] --del_silence: True
[2020-06-23 06:30:41,321 utils.py:21 - info()] --input_reverse: True
[2020-06-23 06:30:41,322 utils.py:21 - info()] --feature_extract_by: librosa
[2020-06-23 06:30:41,322 utils.py:21 - info()] --time_mask_para: 50
[2020-06-23 06:30:41,322 utils.py:21 - info()] --freq_mask_para: 12
[2020-06-23 06:30:41,322 utils.py:21 - info()] --time_mask_num: 2
[2020-06-23 06:30:41,322 utils.py:21 - info()] --freq_mask_num: 2
[2020-06-23 06:30:41,322 utils.py:21 - info()] --dataset_path: ../../DATA/KsponSpeech_01/KsponSpeech_0001/
[2020-06-23 06:30:41,322 utils.py:21 - info()] --data_list_path: ../data/data_list/toy_test_list.csv
[2020-06-23 06:30:41,322 utils.py:21 - info()] --label_path: ./data/label/aihub_labels.csv
[2020-06-23 06:30:41,322 utils.py:21 - info()] --num_workers: 4
[2020-06-23 06:30:41,322 utils.py:21 - info()] --use_cuda: True
[2020-06-23 06:30:41,322 utils.py:21 - info()] --model_path: ../data/checkpoints/model.pt
[2020-06-23 06:30:41,322 utils.py:21 - info()] --batch_size: 1
[2020-06-23 06:30:41,322 utils.py:21 - info()] --decode: greedy
[2020-06-23 06:30:41,323 utils.py:21 - info()] --k: 5
[2020-06-23 06:30:41,323 utils.py:21 - info()] --print_every: 10
[2020-06-23 06:30:41,381 utils.py:21 - info()] Operating System : Linux 4.19.104+
[2020-06-23 06:30:41,381 utils.py:21 - info()] Processor : x86_64
[2020-06-23 06:30:41,388 utils.py:21 - info()] device : Tesla K80
[2020-06-23 06:30:41,388 utils.py:21 - info()] CUDA is available : True
[2020-06-23 06:30:41,388 utils.py:21 - info()] CUDA version : 10.1
[2020-06-23 06:30:41,388 utils.py:21 - info()] PyTorch version : 1.5.1+cu101
[2020-06-23 06:31:03,233 utils.py:141 - _init_num_threads()] NumExpr defaulting to 2 threads.
100% 167/167 [04:18<00:00,  1.55s/it]
[2020-06-23 06:35:21,369 utils.py:21 - info()] evaluate() start
cuda
Traceback (most recent call last):
  File "./eval.py", line 66, in <module>
    main()
  File "./eval.py", line 62, in main
    inference(opt)
  File "./eval.py", line 42, in inference
    evaluator.evaluate(model)
  File "../kospeech/evaluator/evaluator.py", line 43, in evaluate
    cer = self.decoder.search(model, eval_queue, self.device, self.print_every)
  File "../kospeech/decode/search.py", line 42, in search
    output, _ = model(inputs, input_lengths, teacher_forcing_ratio=0.0, language_model=self.language_model)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 151, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 162, in scatter
    return scatter_kwargs(inputs, kwargs, device_ids, dim=self.dim)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/scatter_gather.py", line 36, in scatter_kwargs
    inputs = scatter(inputs, target_gpus, dim) if inputs else []
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/scatter_gather.py", line 28, in scatter
    res = scatter_map(inputs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/scatter_gather.py", line 15, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/scatter_gather.py", line 13, in scatter_map
    return Scatter.apply(target_gpus, None, dim, obj)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/_functions.py", line 88, in forward
    streams = [_get_stream(device) for device in target_gpus]
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/_functions.py", line 88, in <listcomp>
    streams = [_get_stream(device) for device in target_gpus]
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/_functions.py", line 115, in _get_stream
    if _streams[device] is None:
IndexError: list index out of range
```

**Comment by sooftware** [comment]
로컬에서는 GPU 1개인 경우도 잘 돌아갑니다.   
아마 코랩 환경이랑 충돌이 일어나는 것 같은데, 제가 코랩을 사용하지 않아서  
답을 드리기가 어려울 것 같습니다.  
  
저희 코드는 GPU가 1개인 경우도 동작하게 짜여 있습니다.  
코랩은 어떤지 모르겠으나, CUDA_VISIBLE_DEVICE 같이 GPU를 지정해주는 방법을 한 번 알아보시는게 좋을 것 같네요.

**Comment by ur-luella** [comment]
아 그렇군요~
따로 찾아봐야겠네요! 답변 감사드립니다!!
