### ISSUE TITLE
IndexError: list index out of range가 납니다ㅠ

### ISSUE THREAD

**Issue by ur-luella** [sooftware/KoSpeech#29]
안녕하세요.
가장 최근에 보내주신 pre-trained weight와 코드를 이용하여
eval.sh를 돌려보았으나 여전히 indexerror가 나서요ㅠ
돌려보셨을때 이상 없으셨나요?? model과 코드 싱크가 맞지 않는건가 고민이 되어서요!

추가로 보내주신 model에는 
- MaskConv가 아닌 MaskCNN으로 되어있어 model 폴더의 convoultional.py에서 MaskCNN으로 수정하였고
- data폴더의 preprocess 폴더에서 parser.py에 librosa가 import 되어있지 않아 define이 안되어서 추가로 import하였습니다!

```python
[2020-07-03 11:36:12,863 utils.py:21 - info()] --mode: eval
[2020-07-03 11:36:12,863 utils.py:21 - info()] --feature: mel
[2020-07-03 11:36:12,863 utils.py:21 - info()] --sample_rate: 16000
[2020-07-03 11:36:12,863 utils.py:21 - info()] --window_size: 20
[2020-07-03 11:36:12,863 utils.py:21 - info()] --stride: 10
[2020-07-03 11:36:12,863 utils.py:21 - info()] --n_mels: 80
[2020-07-03 11:36:12,863 utils.py:21 - info()] --normalize: True
[2020-07-03 11:36:12,863 utils.py:21 - info()] --del_silence: True
[2020-07-03 11:36:12,863 utils.py:21 - info()] --input_reverse: True
[2020-07-03 11:36:12,863 utils.py:21 - info()] --feature_extract_by: librosa
[2020-07-03 11:36:12,863 utils.py:21 - info()] --time_mask_para: 50
[2020-07-03 11:36:12,863 utils.py:21 - info()] --freq_mask_para: 12
[2020-07-03 11:36:12,863 utils.py:21 - info()] --time_mask_num: 2
[2020-07-03 11:36:12,863 utils.py:21 - info()] --freq_mask_num: 2
[2020-07-03 11:36:12,863 utils.py:21 - info()] --dataset_path: ../../DATA/KsponSpeech_01/KsponSpeech$
0001/
[2020-07-03 11:36:12,863 utils.py:21 - info()] --data_list_path: ../data/data_list/toy_test_list.csv
[2020-07-03 11:36:12,863 utils.py:21 - info()] --label_path: ./data/label/aihub_labels.csv
[2020-07-03 11:36:12,863 utils.py:21 - info()] --num_workers: 4
[2020-07-03 11:36:12,863 utils.py:21 - info()] --use_cuda: True
[2020-07-03 11:36:12,864 utils.py:21 - info()] --model_path: ../data/checkpoints/KsponSpeech_87.44%.$
t
[2020-07-03 11:36:12,864 utils.py:21 - info()] --batch_size: 1
[2020-07-03 11:36:12,864 utils.py:21 - info()] --decode: greedy
[2020-07-03 11:36:12,864 utils.py:21 - info()] --k: 5
[2020-07-03 11:36:12,864 utils.py:21 - info()] --print_every: 10
[2020-07-03 11:36:12,906 utils.py:21 - info()] Operating System : Linux 4.18.0-193.6.3.el8_2.x86_64
[2020-07-03 11:36:12,906 utils.py:21 - info()] Processor : x86_64
[2020-07-03 11:36:12,909 utils.py:21 - info()] device : GeForce RTX 2080 Ti
[2020-07-03 11:36:12,909 utils.py:21 - info()] device : GeForce RTX 2080 Ti
[2020-07-03 11:36:12,909 utils.py:21 - info()] CUDA is available : True
[2020-07-03 11:36:12,909 utils.py:21 - info()] CUDA version : 10.2
[2020-07-03 11:36:12,909 utils.py:21 - info()] PyTorch version : 1.5.1
100%|███████████████████████████████████████████████████████████| 167/167 [00:00<00:00, 39278.24it/s$
[2020-07-03 11:36:15,344 utils.py:21 - info()] evaluate() start
Traceback (most recent call last):
  File "./eval.py", line 66, in <module>
    main()
  File "./eval.py", line 62, in main
    inference(opt)
  File "./eval.py", line 42, in inference
    evaluator.evaluate(model)
  File "../kospeech/evaluator/evaluator.py", line 43, in evaluate
    cer = self.decoder.search(model, eval_queue, self.device, self.print_every)
  File "../kospeech/decode/search.py", line 41, in search
    teacher_forcing_ratio=0.0, language_model=self.language_model)
  File "/home/stt_py/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __c
all__
    result = self.forward(*input, **kwargs)
  File "/home/stt_py/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 151
, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
  File "/home/stt_py/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 162
, in scatter
    return scatter_kwargs(inputs, kwargs, device_ids, dim=self.dim)
  File "/home/stt_py/.local/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 37
, in scatter_kwargs
    kwargs = scatter(kwargs, target_gpus, dim) if kwargs else []
  File "/home/stt_py/.local/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 28
, in scatter
    res = scatter_map(inputs)
  File "/home/stt_py/.local/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 19
, in scatter_map
    return list(map(type(obj), zip(*map(scatter_map, obj.items()))))
  File "/home/stt_py/.local/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 15
, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/home/stt_py/.local/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 13
, in scatter_map
    return Scatter.apply(target_gpus, None, dim, obj)
  File "/home/stt_py/.local/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 88, in
 forward
    streams = [_get_stream(device) for device in target_gpus]
  File "/home/stt_py/.local/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 88, in
 <listcomp>
    streams = [_get_stream(device) for device in target_gpus]
  File "/home/stt_py/.local/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 115, i
n _get_stream
    if _streams[device] is None:
IndexError: list index out of range
```

**Comment by sooftware** [comment]
일단 해당 모델은 제 기억에 spectrogram 피쳐를 사용했던 것으로 기억합니다.  
--feature 옵션을 'spect' 로 넘겨줘 보실래요?    
그리고 해당 에러는 GPU 관련 에러인 것으로 보입니다.  
  
제가 ur-luella 님의 현재 환경 설정이 어떤지를 모르기 때문에 해당 에러에 대한 답변은 드리기가 어려울 것 같습니다.  
그냥 확인하시고 싶은 경우 모델 device들을 cpu로 바꿔서 테스트해보시는 것을 추천드려요.

**Comment by ur-luella** [comment]
안녕하세요!
주말동안 이것저것 해봤는데 model 저장시에 gpu idx도 함께 저장되는 걸까요?

환경은 colab(gpu 1개), 서버(gpu 2개)에서 진행해봤고 둘다 index out이 뜨더라구요ㅠ
또한 서버에서 학습한 모델을 가지고 colab에서 evaluation을 해봤는데 똑같이 index out이 뜨고
colab에서 학습한 모델은 서버에서 잘 돌아가는 것을 확인하였습니다.

추가로 cpu도 해봤는데 아래와 같이 에러가 뜹니다.
```python
[2020-07-06 08:02:07,754 utils.py:21 - info()] --mode: eval
[2020-07-06 08:02:07,754 utils.py:21 - info()] --sample_rate: 16000
[2020-07-06 08:02:07,754 utils.py:21 - info()] --window_size: 20
[2020-07-06 08:02:07,754 utils.py:21 - info()] --stride: 10
[2020-07-06 08:02:07,754 utils.py:21 - info()] --n_mels: 80
[2020-07-06 08:02:07,754 utils.py:21 - info()] --normalize: True
[2020-07-06 08:02:07,754 utils.py:21 - info()] --del_silence: True
[2020-07-06 08:02:07,754 utils.py:21 - info()] --input_reverse: True
[2020-07-06 08:02:07,755 utils.py:21 - info()] --feature_extract_by: auidotorch
[2020-07-06 08:02:07,755 utils.py:21 - info()] --time_mask_para: 50
[2020-07-06 08:02:07,755 utils.py:21 - info()] --freq_mask_para: 12
[2020-07-06 08:02:07,755 utils.py:21 - info()] --time_mask_num: 2
[2020-07-06 08:02:07,755 utils.py:21 - info()] --freq_mask_num: 2
[2020-07-06 08:02:07,755 utils.py:21 - info()] --dataset_path: ../../DATA/KsponSpeech_01/KsponSpeech_0001/
[2020-07-06 08:02:07,755 utils.py:21 - info()] --data_list_path: ../data/data_list/toy_test_list.csv
[2020-07-06 08:02:07,755 utils.py:21 - info()] --label_path: ./data/label/aihub_labels.csv
[2020-07-06 08:02:07,755 utils.py:21 - info()] --num_workers: 4
[2020-07-06 08:02:07,755 utils.py:21 - info()] --use_cuda: True
[2020-07-06 08:02:07,755 utils.py:21 - info()] --model_path: ../data/checkpoints/KsponSpeech_87.44%.pt
[2020-07-06 08:02:07,755 utils.py:21 - info()] --batch_size: 1
[2020-07-06 08:02:07,755 utils.py:21 - info()] --decode: beam
[2020-07-06 08:02:07,755 utils.py:21 - info()] --k: 5
[2020-07-06 08:02:07,755 utils.py:21 - info()] --print_every: 10
[2020-07-06 08:02:07,862 utils.py:21 - info()] Operating System : Linux 4.19.104+
[2020-07-06 08:02:07,862 utils.py:21 - info()] Processor : x86_64
[2020-07-06 08:02:07,862 utils.py:21 - info()] CUDA is available : False
[2020-07-06 08:02:07,862 utils.py:21 - info()] PyTorch version : 1.5.1+cu101
[2020-07-06 08:02:18,641 utils.py:141 - _init_num_threads()] NumExpr defaulting to 2 threads.
100% 167/167 [01:49<00:00,  1.53it/s]
[2020-07-06 08:04:07,726 utils.py:21 - info()] evaluate() start
Traceback (most recent call last):
  File "./eval.py", line 66, in <module>
    main()
  File "./eval.py", line 62, in main
    inference(opt)
  File "./eval.py", line 42, in inference
    evaluator.evaluate(model)
  File "../kospeech/evaluator/evaluator.py", line 43, in evaluate
    cer = self.decoder.search(model, eval_queue, self.device, self.print_every)
  File "../kospeech/decode/search.py", line 81, in search
    return super(BeamSearch, self).search(model, queue, device, print_every)
  File "../kospeech/decode/search.py", line 41, in search
    teacher_forcing_ratio=0.0, language_model=self.language_model)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 149, in forward
    "them on device: {}".format(self.src_device_obj, t.device))
RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cpu
```

**Comment by ur-luella** [comment]
안녕하세요!
위와 같은 에러를 해결하려다 보니 model을 단순히 torch.save하는 경우에
사용된 특정 class 및 directory에 바인딩되는 문제가 있다고 합니다.
https://discuss.pytorch.org/t/how-could-i-train-on-multi-gpu-and-infer-with-single-gpu/22838/5

그래서 model을 저장할땐 torch.save(model.state_dict())로 저장한 후
로드할 땐 torch.load_state_dict(torch.load(path))로 pytorch에서 권장하고 있는데
https://pytorch.org/docs/master/notes/serialization.html

이 부분을 진행해보려고 pre-trained model을 불러와 state_dict()를 따로 저장한 후에
아래의 코드처럼 model의 class를 가져와서 load해보려합니다.
```python
the_model = TheModelClass(*args, **kwargs)
```
제가 아직 실력이 좋지 않아 이 부분에서 막혔는데
여기서 말하는 class가 train후 model과 함께 저장되는 trainer_states를 얘기하는걸까요?

맞다면 model 저장할때 함께 저장되는 trainer_states를 받을 수 있을까요??
