### ISSUE TITLE
multi gpu 학습 후 single gpu 또는 cpu inference 시에 gpu index error가 납니다

### ISSUE THREAD

**Issue by ur-luella** [sooftware/KoSpeech#32]
안녕하세요. 
29번 이슈를 올렸었는데 제가 답이 느려서인지 close됐더라구요ㅠㅠ
그뒤로도 글을 올렸으나 혹시 알림이 가지 않을까하여 다시 올립니다.

말씀해주신대로 spect로 넘겨서도 진행해봤고
gpu 2개인 서버로 학습 후 colab gpu 1개로 inference해봤는데 같은 에러인 index out이 뜨고
colab에서 학습한 모델은 서버에서 잘 돌아가는 것을 확인하였습니다.

추가로 주신 pre-trained model을 가지고 cpu로 해봤는데 아래와 같은 에러가 뜹니다.

```python
[2020-07-06 08:02:07,754 utils.py:21 - info()] --mode: eval
[2020-07-06 08:02:07,754 utils.py:21 - info()] --sample_rate: 16000
[2020-07-06 08:02:07,754 utils.py:21 - info()] --window_size: 20
[2020-07-06 08:02:07,754 utils.py:21 - info()] --stride: 10
[2020-07-06 08:02:07,754 utils.py:21 - info()] --n_mels: 80
[2020-07-06 08:02:07,754 utils.py:21 - info()] --normalize: True
[2020-07-06 08:02:07,754 utils.py:21 - info()] --del_silence: True
[2020-07-06 08:02:07,754 utils.py:21 - info()] --input_reverse: True
[2020-07-06 08:02:07,755 utils.py:21 - info()] --feature_extract_by: auidotorch
[2020-07-06 08:02:07,755 utils.py:21 - info()] --time_mask_para: 50
[2020-07-06 08:02:07,755 utils.py:21 - info()] --freq_mask_para: 12
[2020-07-06 08:02:07,755 utils.py:21 - info()] --time_mask_num: 2
[2020-07-06 08:02:07,755 utils.py:21 - info()] --freq_mask_num: 2
[2020-07-06 08:02:07,755 utils.py:21 - info()] --dataset_path: ../../DATA/KsponSpeech_01/KsponSpeech_0001/
[2020-07-06 08:02:07,755 utils.py:21 - info()] --data_list_path: ../data/data_list/toy_test_list.csv
[2020-07-06 08:02:07,755 utils.py:21 - info()] --label_path: ./data/label/aihub_labels.csv
[2020-07-06 08:02:07,755 utils.py:21 - info()] --num_workers: 4
[2020-07-06 08:02:07,755 utils.py:21 - info()] --use_cuda: True
[2020-07-06 08:02:07,755 utils.py:21 - info()] --model_path: ../data/checkpoints/KsponSpeech_87.44%.pt
[2020-07-06 08:02:07,755 utils.py:21 - info()] --batch_size: 1
[2020-07-06 08:02:07,755 utils.py:21 - info()] --decode: beam
[2020-07-06 08:02:07,755 utils.py:21 - info()] --k: 5
[2020-07-06 08:02:07,755 utils.py:21 - info()] --print_every: 10
[2020-07-06 08:02:07,862 utils.py:21 - info()] Operating System : Linux 4.19.104+
[2020-07-06 08:02:07,862 utils.py:21 - info()] Processor : x86_64
[2020-07-06 08:02:07,862 utils.py:21 - info()] CUDA is available : False
[2020-07-06 08:02:07,862 utils.py:21 - info()] PyTorch version : 1.5.1+cu101
[2020-07-06 08:02:18,641 utils.py:141 - _init_num_threads()] NumExpr defaulting to 2 threads.
100% 167/167 [01:49<00:00,  1.53it/s]
[2020-07-06 08:04:07,726 utils.py:21 - info()] evaluate() start
Traceback (most recent call last):
  File "./eval.py", line 66, in <module>
    main()
  File "./eval.py", line 62, in main
    inference(opt)
  File "./eval.py", line 42, in inference
    evaluator.evaluate(model)
  File "../kospeech/evaluator/evaluator.py", line 43, in evaluate
    cer = self.decoder.search(model, eval_queue, self.device, self.print_every)
  File "../kospeech/decode/search.py", line 81, in search
    return super(BeamSearch, self).search(model, queue, device, print_every)
  File "../kospeech/decode/search.py", line 41, in search
    teacher_forcing_ratio=0.0, language_model=self.language_model)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 149, in forward
    "them on device: {}".format(self.src_device_obj, t.device))
RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cpu
```

구글링해봤을때 model을 단순히 torch.save하는 경우에
사용된 특정 class 및 directory에 바인딩되는 문제가 있다고 합니다.
https://discuss.pytorch.org/t/how-could-i-train-on-multi-gpu-and-infer-with-single-gpu/22838/5

그래서 model을 저장할땐 torch.save(model.state_dict())로 저장한 후
로드할 땐 torch.load_state_dict(torch.load(path))로 pytorch에서 권장하고 있는데
https://pytorch.org/docs/master/notes/serialization.html

이 부분을 진행해보려고 pre-trained model을 불러와 state_dict()를 따로 저장한 후에
아래의 코드처럼 model의 class를 가져와서 load해보려합니다.

the_model = TheModelClass(*args, **kwargs)
이 부분에서 막혔는데 여기서 말하는 class가 train후 model과 함께 저장되는 trainer_states를 얘기하는걸까요?

맞다면 model 저장할때 함께 저장되는 trainer_states를 받을 수 있을까요??

감사합니다!

**Comment by sooftware** [comment]
음... 말씀하신 방법이랑 결국 같은 방법이긴한데 아래와 같은 방법으로 진행해 보실래요?   

```python
model = ListenAttendSpell(set hyperparameters)
model.load_state_dict(torch.load('pretrain path').state_dict())
```
  
그리고 언급해주신 TheModelClass는 위와 같이 새로 모델 클래스를 생성하라는 의미이고, trainer_states와는 관련이 없습니다.

**Comment by sooftware** [comment]
그리고 gpu, cpu 관련 문제는, 모델의 멤버 변수인 device는 'cuda'로 설정되어 있는데, 'cpu'에서 실행하려고 해서 나는 문제라고 생각됩니다. cuda면 cuda로 전체를 통일하셔야 하고, cpu면 모델 전체적으로 cpu로 통일해주셔야 합니다.  
  
제가 직접 코드 에러를 보면서 해결하면 금방될 일인데, 이렇게 이슈로 주고받아보니 직접적인 도움을 드리기가 어렵네요.  ㅠ.ㅠ  
공부한다고 생각하시고 (사실 이 부분이 처음하면 어렵긴합니다..) 한번 에러코드 읽어보시면서 해결해보시면 생각보다 쉽게 해결될 겁니다.

**Comment by ur-luella** [comment]
아 그렇군요! 시도해보겠습니다!
친절하게 설명해주셔서 감사합니다!
많은 도움 됐습니다!! ㅎㅎ
