### ISSUE TITLE
AttributeError: While running eval.py

### ISSUE THREAD

**Issue by elyorman** [sooftware/KoSpeech#35]
`(base) C:\Users\Admin\ELYOR\kospeech\KoSpeech-master>python eval.py
[2020-07-19 17:58:02,235 utils.py:21 - info()] --mode: eval
[2020-07-19 17:58:02,236 utils.py:21 - info()] --transform_method: mel
[2020-07-19 17:58:02,236 utils.py:21 - info()] --sample_rate: 16000
[2020-07-19 17:58:02,236 utils.py:21 - info()] --window_size: 20
[2020-07-19 17:58:02,237 utils.py:21 - info()] --stride: 10
[2020-07-19 17:58:02,237 utils.py:21 - info()] --n_mels: 80
[2020-07-19 17:58:02,238 utils.py:21 - info()] --normalize: False
[2020-07-19 17:58:02,238 utils.py:21 - info()] --del_silence: False
[2020-07-19 17:58:02,238 utils.py:21 - info()] --input_reverse: False
[2020-07-19 17:58:02,238 utils.py:21 - info()] --feature_extract_by: librosa
[2020-07-19 17:58:02,238 utils.py:21 - info()] --time_mask_para: 50
[2020-07-19 17:58:02,239 utils.py:21 - info()] --freq_mask_para: 12
[2020-07-19 17:58:02,239 utils.py:21 - info()] --time_mask_num: 2
[2020-07-19 17:58:02,239 utils.py:21 - info()] --freq_mask_num: 2
[2020-07-19 17:58:02,239 utils.py:21 - info()] --dataset_path: /data1/
[2020-07-19 17:58:02,239 utils.py:21 - info()] --data_list_path: ./data/data_list/filter_train_list.csv
[2020-07-19 17:58:02,239 utils.py:21 - info()] --label_path: ./data/label/aihub_labels.csv
[2020-07-19 17:58:02,239 utils.py:21 - info()] --num_workers: 4
[2020-07-19 17:58:02,239 utils.py:21 - info()] --use_cuda: False
[2020-07-19 17:58:02,240 utils.py:21 - info()] --model_path: None
[2020-07-19 17:58:02,240 utils.py:21 - info()] --batch_size: 1
[2020-07-19 17:58:02,240 utils.py:21 - info()] --decode: greedy
[2020-07-19 17:58:02,240 utils.py:21 - info()] --k: 5
[2020-07-19 17:58:02,240 utils.py:21 - info()] --print_every: 10
[2020-07-19 17:58:02,240 utils.py:21 - info()] Operating System : Windows 10
[2020-07-19 17:58:02,240 utils.py:21 - info()] Processor : Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
[2020-07-19 17:58:02,269 utils.py:21 - info()] CUDA is available : True
[2020-07-19 17:58:02,270 utils.py:21 - info()] PyTorch version : 1.5.1
Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\lib\site-packages\torch\serialization.py", line 311, in _check_seekable
    f.seek(f.tell())
AttributeError: 'NoneType' object has no attribute 'seek'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "eval.py", line 58, in <module>
    main()
  File "eval.py", line 54, in main
    inference(opt)
  File "eval.py", line 25, in inference
    model = load_test_model(opt, device)
  File "C:\Users\Admin\ELYOR\kospeech\KoSpeech-master\kospeech\model_builder.py", line 118, in load_test_model
    model = torch.load(opt.model_path, map_location=lambda storage, loc: storage).to(device)
  File "C:\Users\Admin\anaconda3\lib\site-packages\torch\serialization.py", line 584, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\Admin\anaconda3\lib\site-packages\torch\serialization.py", line 239, in _open_file_like
    return _open_buffer_reader(name_or_buffer)
  File "C:\Users\Admin\anaconda3\lib\site-packages\torch\serialization.py", line 224, in __init__
    _check_seekable(buffer)
  File "C:\Users\Admin\anaconda3\lib\site-packages\torch\serialization.py", line 314, in _check_seekable
    raise_err_msg(["seek", "tell"], e)
  File "C:\Users\Admin\anaconda3\lib\site-packages\torch\serialization.py", line 307, in raise_err_msg
    raise type(e)(msg)
AttributeError: 'NoneType' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.`

**Comment by sooftware** [comment]
Please check if the model path is set properly.

**Comment by elyorman** [comment]
Hello. I guess the error was coming from main.py. The model is not training. Could we talk on kakaotalk if you are ok?

**Comment by sooftware** [comment]
https://gitter.im/Korean-Speech-Recognition/community  
I think we should talk here.
