### ISSUE TITLE
[Train Error] return_decode_dict 에러 

### ISSUE THREAD

**Issue by minlom** [sooftware/KoSpeech#38]
안녕하세요, 공유해주신 코드로 train 중에 아래와 같은 에러가 발생하여 확인 요청드립니다.

train 모드에서 첫 번째 에폭의 train까지는 완료가 되었고 validation에서 에러가 발생하였습니다.
에러는 return_decode_dict가 forward()에서 unexpected argument라는 것인데 이전에 코드에서는 없던 argument로 보입니다.
현재 기동한 코드는 금일 새롭게 clone 하였습니다.
기동 모델은 seq2seq인데 혹시 추가로 설정해야 할 것이 있을까요?

**에러 발생 코드 - supervised_trainer.py**
                if self.architecture == 'seq2seq':
                    model.module.flatten_parameters()

                    output = model(inputs=inputs, input_lengths=input_lengths,
                                   teacher_forcing_ratio=0.0,
                                   language_model=None, return_decode_dict=False)

**에러 메시지**

Traceback (most recent call last):
  File "./main.py", line 92, in main
    train(opt)
  File "./main.py", line 71, in train
    num_epochs=opt.num_epochs, teacher_forcing_ratio=opt.teacher_forcing_ratio, resume=opt.resume)
  File "../kospeech/trainer/supervised_trainer.py", line 151, in train
    valid_cer = self.validate(model, valid_queue)
  File "../kospeech/trainer/supervised_trainer.py", line 303, in validate
    language_model=None, return_decode_dict=False)
  File "/home/mchoe/.conda/envs/sr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mchoe/.conda/envs/sr/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/mchoe/.conda/envs/sr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'return_decode_dict'

 **전체 로그**
[2020-07-28 17:05:02,639 utils.py:21 - info()] --mode: train
[2020-07-28 17:05:02,639 utils.py:21 - info()] --transform_method: mel
[2020-07-28 17:05:02,639 utils.py:21 - info()] --sample_rate: 16000
[2020-07-28 17:05:02,639 utils.py:21 - info()] --frame_length: 20
[2020-07-28 17:05:02,639 utils.py:21 - info()] --frame_shift: 10
[2020-07-28 17:05:02,639 utils.py:21 - info()] --n_mels: 80
[2020-07-28 17:05:02,639 utils.py:21 - info()] --normalize: True
[2020-07-28 17:05:02,639 utils.py:21 - info()] --del_silence: True
[2020-07-28 17:05:02,639 utils.py:21 - info()] --input_reverse: False
[2020-07-28 17:05:02,639 utils.py:21 - info()] --feature_extract_by: torchaudio
[2020-07-28 17:05:02,639 utils.py:21 - info()] --time_mask_para: 40
[2020-07-28 17:05:02,639 utils.py:21 - info()] --freq_mask_para: 12
[2020-07-28 17:05:02,639 utils.py:21 - info()] --time_mask_num: 2
[2020-07-28 17:05:02,639 utils.py:21 - info()] --freq_mask_num: 2
[2020-07-28 17:05:02,639 utils.py:21 - info()] --architecture: seq2seq
[2020-07-28 17:05:02,639 utils.py:21 - info()] --use_bidirectional: True
[2020-07-28 17:05:02,639 utils.py:21 - info()] --mask_conv: False
[2020-07-28 17:05:02,639 utils.py:21 - info()] --hidden_dim: 512
[2020-07-28 17:05:02,639 utils.py:21 - info()] --dropout: 0.3
[2020-07-28 17:05:02,639 utils.py:21 - info()] --attn_mechanism: multi-head
[2020-07-28 17:05:02,639 utils.py:21 - info()] --num_heads: 4
[2020-07-28 17:05:02,639 utils.py:21 - info()] --label_smoothing: 0.1
[2020-07-28 17:05:02,639 utils.py:21 - info()] --num_encoder_layers: 3
[2020-07-28 17:05:02,639 utils.py:21 - info()] --num_decoder_layers: 2
[2020-07-28 17:05:02,640 utils.py:21 - info()] --extractor: vgg
[2020-07-28 17:05:02,640 utils.py:21 - info()] --activation: hardtanh
[2020-07-28 17:05:02,640 utils.py:21 - info()] --rnn_type: lstm
[2020-07-28 17:05:02,640 utils.py:21 - info()] --teacher_forcing_ratio: 1.0
[2020-07-28 17:05:02,640 utils.py:21 - info()] --dataset_path: /home/mchoe/sr/data/
[2020-07-28 17:05:02,640 utils.py:21 - info()] --data_list_path: /home/mchoe/PycharmProjects/sr/data/data_list/filter_train_list_1000.csv
[2020-07-28 17:05:02,640 utils.py:21 - info()] --label_path: /home/mchoe/PycharmProjects/sr/verf/aihub_label_table.dat
[2020-07-28 17:05:02,640 utils.py:21 - info()] --spec_augment: True
[2020-07-28 17:05:02,640 utils.py:21 - info()] --noise_augment: False
[2020-07-28 17:05:02,640 utils.py:21 - info()] --noiseset_size: 1000
[2020-07-28 17:05:02,640 utils.py:21 - info()] --noise_level: 0.7
[2020-07-28 17:05:02,640 utils.py:21 - info()] --use_cuda: True
[2020-07-28 17:05:02,640 utils.py:21 - info()] --batch_size: 16
[2020-07-28 17:05:02,640 utils.py:21 - info()] --num_workers: 1
[2020-07-28 17:05:02,640 utils.py:21 - info()] --num_epochs: 10
[2020-07-28 17:05:02,640 utils.py:21 - info()] --init_lr: 3e-05
[2020-07-28 17:05:02,640 utils.py:21 - info()] --high_plateau_lr: 0.0003
[2020-07-28 17:05:02,640 utils.py:21 - info()] --low_plateau_lr: 1e-05
[2020-07-28 17:05:02,640 utils.py:21 - info()] --decay_threshold: 0.02
[2020-07-28 17:05:02,640 utils.py:21 - info()] --rampup_period: 400
[2020-07-28 17:05:02,640 utils.py:21 - info()] --exp_decay_period: 120000
[2020-07-28 17:05:02,640 utils.py:21 - info()] --valid_ratio: 0.05
[2020-07-28 17:05:02,640 utils.py:21 - info()] --max_len: 120
[2020-07-28 17:05:02,640 utils.py:21 - info()] --max_grad_norm: 400
[2020-07-28 17:05:02,640 utils.py:21 - info()] --teacher_forcing_step: 0.02
[2020-07-28 17:05:02,640 utils.py:21 - info()] --min_teacher_forcing_ratio: 0.8
[2020-07-28 17:05:02,640 utils.py:21 - info()] --seed: 7
[2020-07-28 17:05:02,640 utils.py:21 - info()] --save_result_every: 1000
[2020-07-28 17:05:02,640 utils.py:21 - info()] --checkpoint_every: 5000
[2020-07-28 17:05:02,640 utils.py:21 - info()] --print_every: 10
[2020-07-28 17:05:02,640 utils.py:21 - info()] --resume: False
[2020-07-28 17:05:02,644 utils.py:21 - info()] Operating System : Linux 5.3.0-61-generic
[2020-07-28 17:05:02,644 utils.py:21 - info()] Processor : x86_64
[2020-07-28 17:05:02,644 utils.py:21 - info()] device : GeForce GTX 1080 Ti
[2020-07-28 17:05:02,644 utils.py:21 - info()] CUDA is available : True
[2020-07-28 17:05:02,644 utils.py:21 - info()] CUDA version : 10.2
[2020-07-28 17:05:02,644 utils.py:21 - info()] PyTorch version : 1.5.1
[2020-07-28 17:05:02,668 utils.py:21 - info()] split dataset start !!
[2020-07-28 17:05:02,669 utils.py:21 - info()] Applying Spec Augmentation...
[2020-07-28 17:05:02,671 utils.py:21 - info()] split dataset complete !!
[2020-07-28 17:05:04,159 utils.py:21 - info()] start
[2020-07-28 17:05:04,160 utils.py:21 - info()] Epoch 0 start
[2020-07-28 17:05:11,096 utils.py:21 - info()] timestep:   10/ 118, loss: 0.6336, cer: 2.93, elapsed: 6.93s 0.12m 0.00h
[2020-07-28 17:05:17,344 utils.py:21 - info()] timestep:   20/ 118, loss: 0.6474, cer: 3.00, elapsed: 6.25s 0.22m 0.00h
[2020-07-28 17:05:24,735 utils.py:21 - info()] timestep:   30/ 118, loss: 0.6424, cer: 2.98, elapsed: 7.39s 0.34m 0.01h
[2020-07-28 17:05:31,703 utils.py:21 - info()] timestep:   40/ 118, loss: 0.6430, cer: 2.96, elapsed: 6.97s 0.46m 0.01h
[2020-07-28 17:05:38,761 utils.py:21 - info()] timestep:   50/ 118, loss: 0.6420, cer: 2.92, elapsed: 7.06s 0.58m 0.01h
[2020-07-28 17:05:45,136 utils.py:21 - info()] timestep:   60/ 118, loss: 0.6403, cer: 2.90, elapsed: 6.37s 0.68m 0.01h
[2020-07-28 17:05:52,177 utils.py:21 - info()] timestep:   70/ 118, loss: 0.6372, cer: 2.89, elapsed: 7.04s 0.80m 0.01h
[2020-07-28 17:05:59,013 utils.py:21 - info()] timestep:   80/ 118, loss: 0.6334, cer: 2.82, elapsed: 6.84s 0.91m 0.02h
[2020-07-28 17:06:06,097 utils.py:21 - info()] timestep:   90/ 118, loss: 0.6271, cer: 2.75, elapsed: 7.08s 1.03m 0.02h
[2020-07-28 17:06:13,275 utils.py:21 - info()] timestep:  100/ 118, loss: 0.6205, cer: 2.58, elapsed: 7.18s 1.15m 0.02h
[2020-07-28 17:06:19,938 utils.py:21 - info()] timestep:  110/ 118, loss: 0.6141, cer: 2.44, elapsed: 6.66s 1.26m 0.02h
batch complete
[2020-07-28 17:06:26,965 utils.py:21 - info()] save checkpoints
/home/mchoe/PycharmProjects/sr4/data/checkpoint/checkpoints/2020_07_28_17_06_26/trainer_states.pt
/home/mchoe/PycharmProjects/sr4/data/checkpoint/checkpoints/2020_07_28_17_06_26/model.pt
[2020-07-28 17:06:26,965 utils.py:21 - info()] train() completed
[2020-07-28 17:06:27,585 utils.py:21 - info()] save checkpoints
/home/mchoe/PycharmProjects/sr4/data/checkpoint/checkpoints/2020_07_28_17_06_26/trainer_states.pt
/home/mchoe/PycharmProjects/sr4/data/checkpoint/checkpoints/2020_07_28_17_06_26/model.pt
[2020-07-28 17:06:27,586 utils.py:21 - info()] Epoch 0 (Training) Loss 0.6065 CER 2.3189
duration per epoch :  83.42599272727966
[2020-07-28 17:06:27,586 utils.py:21 - info()] validate() start
  File "./main.py", line 96, in <module>
    main()
  File "./main.py", line 92, in main
    train(opt)
  File "./main.py", line 71, in train
    num_epochs=opt.num_epochs, teacher_forcing_ratio=opt.teacher_forcing_ratio, resume=opt.resume)
  File "../kospeech/trainer/supervised_trainer.py", line 151, in train
    valid_cer = self.validate(model, valid_queue)
  File "../kospeech/trainer/supervised_trainer.py", line 310, in validate
    language_model=None, return_decode_dict=False)
  File "/home/mchoe/.conda/envs/sr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mchoe/.conda/envs/sr/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/mchoe/.conda/envs/sr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'return_decode_dict'

**Comment by sooftware** [comment]
안녕하세요.  
이슈 남겨주셔서 감사합니다.

해당 버그 확인 후 조치하였습니다.
return_decode_dict 변수명을 return_dec_dict로 잘못 지정하여 발생한 오류였습니다.

kospeech/models/seq2seq/seq2seq.py의 return_dec_dict => return_decode_dict로 수정해주시면 됩니다.

**Comment by minlom** [comment]
전달해주신 내역으로 수정하니 정상적으로 train 되는 것을 확인하였습니다.
감사합니다!!
