### ISSUE TITLE
train 시 epoch이 넘어갈때 out of memory error

### ISSUE THREAD

**Issue by ur-luella** [sooftware/KoSpeech#49]
안녕하세요!
최신 코드로 train 시도를 하고 있는데 다음 epoch으로 넘어갈때마다 out of memory error가 뜹니다.
혹시 제가 개선할 수 있는 방안이 있을까요?
사용하고 있는 GPU는 RTX 2080Ti 2개에 RAM 256GB입니다!
 ```python
Traceback (most recent call last):
  File "./main.py", line 113, in <module>
    main()
  File "./main.py", line 109, in main
    train(opt)
  File "./main.py", line 87, in train
    resume=opt.resume
  File "../kospeech/trainer/supervised_trainer.py", line 147, in train
    train_queue, teacher_forcing_ratio)
  File "../kospeech/trainer/supervised_trainer.py", line 230, in __train_epoches
    targets=targets, teacher_forcing_ratio=teacher_forcing_ratio)
  File "/home/stt_py/.local/lib/python3.6/site-packages/torch/nn/modules/module.
py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/stt_py/.local/lib/python3.6/site-packages/torch/nn/parallel/data_p
arallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/stt_py/.local/lib/python3.6/site-packages/torch/nn/parallel/data_p
arallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replica
s)])
  File "/home/stt_py/.local/lib/python3.6/site-packages/torch/nn/parallel/parall
el_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/stt_py/.local/lib/python3.6/site-packages/torch/_utils.py", line 3
95, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/home/stt_py/.local/lib/python3.6/site-packages/torch/nn/parallel/parall
el_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/stt_py/.local/lib/python3.6/site-packages/torch/nn/modules/module.
py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "../kospeech/models/acoustic/seq2seq/seq2seq.py", line 51, in forward
    result = self.decoder(targets, output, teacher_forcing_ratio, return_decode_
dict)
  File "/home/stt_py/.local/lib/python3.6/site-packages/torch/nn/modules/module.
py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "../kospeech/models/acoustic/seq2seq/decoder.py", line 175, in forward
    step_output, hidden, attn = self.forward_step(input_var, hidden, encoder_out
puts, attn)
  File "../kospeech/models/acoustic/seq2seq/decoder.py", line 121, in forward_st
ep
    output, hidden = self.rnn(embedded, hidden)
  File "/home/stt_py/.local/lib/python3.6/site-packages/torch/nn/modules/module.
py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/stt_py/.local/lib/python3.6/site-packages/torch/nn/modules/rnn.py"
, line 570, in forward
    self.dropout, self.training, self.bidirectional, self.batch_first)
RuntimeError: CUDA out of memory. Tried to allocate 66.00 MiB (GPU 1; 10.76 GiB
total capacity; 9.39 GiB already allocated; 54.44 MiB free; 9.82 GiB reserved in
 total by PyTorch)
```

**Comment by sooftware** [comment]
이 문제는 저희도 왜 그런지 자세히는 파악을 못하고 있습니다 ㅠ.ㅠ  
까먹고 있다가 이슈 남겨주셔서 매 에폭마다 torch.cuda.empty_cache()를 호출해주도록 수정은 해봤습니다만,   
효과가 있을지에 대해서는 잘 모르겠네요.

**Comment by ur-luella** [comment]
여전히 에러가 나네요ㅠ 조금 더 확인이 필요할 것 같습니다ㅠ

**Comment by qute012** [comment]
@sooftware 
최신 코드를 자세히  본 것은 아니지만, batch size를 많이 줄여서 학습할 때, 메모리가 계속해서 증가하면 미니 배치를 만드는 collate_fn 역할을 하는 함수를 확인해볼 필요가 있어보이네요.

**Comment by sooftware** [comment]
@qute012 안녕하세요 덕진님. 음.. 예전에는 안 나던 에러가 갑자기 나서 제가 어딘가 잘못 수정한거 같은데 요즘 이 프로젝트에 신경을 못 써서 확인을 못하고 있네요 ㅠ.ㅠ

**Comment by Minhyuk-Jung** [comment]
혹시 해결방안 찾으신 분 있으신가요?
KoSpeech를 알게되서 처음 음성인식를 시도해보는데 몇일째 같은문제로 진행을 못하고 있네요.
pytorch도 처음써봐서 여기저기 이슈들 구글링해서 되는대로 적용해보는데 다 소용이 없네요ㅜ
cuda10.1버전으로 진행중이고요, PC사양은 윗분이랑 거의 같은 사양입니다.

**Comment by sooftware** [comment]
안녕하세요! 해당 에러를 해결해야 하는데, 최근 다른 일이 바쁘다보니 디버깅을 못하고 있네요...  
SupervisedTrainer 클래스의 train()쪽을 살펴보면 될 것 같습니다.  
  
저도 시간 될 때 디버깅을 시도해보겠습니다.  
죄송합니다.

**Comment by Minhyuk-Jung** [comment]
바쁘실텐데 빠른답변 감사드립니다. 
디버깅으로 끊어가면서 메모리 증감량을 보고 있는데 파이토치초보라 아직 원인을 못찾았네요..
__train_epoches()에 loop돌아가는 어딘가인거 같은데 찾게되면 연락드리겠습니다.
혹시 저보다 빨리 해결하시거든 꼭 알려주십시오.

**Comment by sooftware** [comment]
저는 학습 돌려본 결과 OOM 에러가 따로 나지 않았습니다. 혹시 지금도 돌렸을 때 에러가 날까요?

**Comment by sooftware** [comment]
이후로도 학습을 돌렸본 결과 OOM 에러가 따로 나지 않습니다.  정확한 원인은 파악하지 못했으나, 토치 버젼 등의 문제일 수도 있어보이네요.
