### ISSUE TITLE
ModuleNotFoundError: No module named 'kospeech.models.acoustic'

### ISSUE THREAD

**Issue by woo1** [sooftware/KoSpeech#51]
안녕하세요 README에 링크된 pretrained model 로 infer.sh 파일을 실행하면 해당 에러가 발생합니다.
kospeech.models 폴더 내에 acoustic 관련 파일이 업로드 되지 않아서 그런 게 아닌지 문의드립니다.
시간이 되신다면 한번 확인해주시면 감사하겠습니다.

아래는 에러 로그입니다.
Traceback (most recent call last):
  File "run_pretrain.py", line 33, in <module>
    model = load_test_model(opt, opt.device)
  File "../kospeech/model_builder.py", line 201, in load_test_model
    model = torch.load(opt.model_path, map_location=lambda storage, loc: storage).to(device)
  File "/KoSpeech/venv/lib/python3.7/site-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/KoSpeech/venv/lib/python3.7/site-packages/torch/serialization.py", line 702, in _legacy_load
    result = unpickler.load()
ModuleNotFoundError: No module named 'kospeech.models.acoustic'

**Comment by sooftware** [comment]
당시 학습때와 폴더구조가 상이하여 나오는 문제 같습니다.  
저장된 Key들을 조금 수정해주어야 할 것 같습니다.  
  
pt 파일을 load하시고 key 들을 확인하여 조금만 수정해주시면 정상 작동 할 것으로 보입니다.

**Comment by kts12345** [comment]
load 가 안된다는 질문인데
load 후 key를 수정하라는 답변이 적절하지 않아 보입니다.
